### ISSUE TITLE
显示no mudule named 'past'

### ISSUE THREAD

**Issue by buloseshi** [bubbliiiing/centernet-pytorch#35]
Traceback (most recent call last):
  File "train.py", line 15, in <module>
    from utils.callbacks import LossHistory
  File "/root/centernet/centernet-pytorch-main/utils/callbacks.py", line 9, in <module>
    from torch.utils.tensorboard import SummaryWriter
  File "/root/.local/lib/python3.7/site-packages/torch/utils/tensorboard/__init__.py", line 6, in <module>
    from .writer import FileWriter, SummaryWriter  # noqa F401
  File "/root/.local/lib/python3.7/site-packages/torch/utils/tensorboard/writer.py", line 18, in <module>
    from ._convert_np import make_np
  File "/root/.local/lib/python3.7/site-packages/torch/utils/tensorboard/_convert_np.py", line 12, in <module>
    from caffe2.python import workspace
  File "/root/.local/lib/python3.7/site-packages/caffe2/python/workspace.py", line 15, in <module>
    from past.builtins import basestring

**Comment by buloseshi** [comment]
不好意思，问这么简单的问题，已通过pip install future 解决
