### ISSUE TITLE
请问我改mobilenetv3的时候运行到第7批次就自动停止了是怎么回事呢

### ISSUE THREAD

**Issue by sunsn1997** [bubbliiiing/centernet-pytorch#44]
Finish Validation
  0%|          | 0/119 [00:00<?, ?it/s]Get map.
  0%|          | 0/119 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/linux/data2/sun/centernet-pytorch-main/train.py", line 491, in <module>
    epoch_step, epoch_step_val, gen, gen_val, UnFreeze_Epoch, Cuda, fp16, scaler, backbone, save_period, save_dir, local_rank)
  File "/home/linux/data2/sun/centernet-pytorch-main/utils/utils_fit.py", line 161, in fit_one_epoch
    eval_callback.on_epoch_end(epoch + 1, model_train)
  File "/home/linux/data2/sun/centernet-pytorch-main/utils/callbacks.py", line 211, in on_epoch_end
    self.get_map_txt(image_id, image, self.class_names, self.map_out_path)
  File "/home/linux/data2/sun/centernet-pytorch-main/utils/callbacks.py", line 145, in get_map_txt
    outputs = decode_bbox(outputs[0], outputs[1], outputs[2], self.confidence, self.cuda)
IndexError: list index out of range

**Comment by sunsn1997** [comment]
是第五批次，评估的时候出现的问题

**Comment by bubbliiiing** [comment]
原库没有吗

**Comment by lkhwhkzz** [comment]
> 是第五批次，评估的时候出现的问题

我也是，你把评估等于5的那个变量设置高点就不会
